### ISSUE TITLE
内推内推

### ISSUE THREAD

**Issue by HungKuei** [gdufeZLYL/springboot-penguin#19]
哈哈，内推还有效吗？帮我推推。我之前改了你的项目做的毕业设计。我的GitHub仓库
https://github.com/HungKuei

**Comment by gdufeZLYL** [comment]
有效

**Comment by gdufeZLYL** [comment]
> 哈哈，内推还有效吗？帮我推推。我之前改了你的项目做的毕业设计。我的GitHub仓库
> https://github.com/HungKuei

有效

**Comment by gdufeZLYL** [comment]
> 哈哈，内推还有效吗？帮我推推。我之前改了你的项目做的毕业设计。我的GitHub仓库
> https://github.com/HungKuei

点进去投简历就好了哈

**Comment by HungKuei** [comment]
> > 哈哈，内推还有效吗？帮我推推。我之前改了你的项目做的毕业设计。我的GitHub仓库
> > https://github.com/HungKuei
> 
> 点进去投简历就好了哈

**Comment by HungKuei** [comment]
> > 哈哈，内推还有效吗？帮我推推。我之前改了你的项目做的毕业设计。我的GitHub仓库
> > https://github.com/HungKuei
> 
> 点进去投简历就好了哈

我是今年六月份毕业的，现在在一家国企下的子公司工作，感觉学不到什么新东西，每天就是CRUD,你这边可以内推吗？将不胜感激，抱拳

**Comment by gdufeZLYL** [comment]
> > > 哈哈，内推还有效吗？帮我推推。我之前改了你的项目做的毕业设计。我的GitHub仓库
> > > https://github.com/HungKuei
> > 
> > 
> > 点进去投简历就好了哈
> 
> 我是今年六月份毕业的，现在在一家国企下的子公司工作，感觉学不到什么新东西，每天就是CRUD,你这边可以内推吗？将不胜感激，抱拳

毕业不到一年内推失败率很高哦

**Comment by HungKuei** [comment]
> > > > 哈哈，内推还有效吗？帮我推推。我之前改了你的项目做的毕业设计。我的GitHub仓库
> > > > https://github.com/HungKuei
> > > 
> > > 
> > > 点进去投简历就好了哈
> > 
> > 
> > 我是今年六月份毕业的，现在在一家国企下的子公司工作，感觉学不到什么新东西，每天就是CRUD,你这边可以内推吗？将不胜感激，抱拳
> 
> 毕业不到一年内推失败率很高哦
试试呗，
